### ISSUE TITLE
Possibly Helpful PlantUML Notes

### ISSUE THREAD

**Issue by KyleKing** [mattjhayes/PlantUML-Examples#1]
Hi! I was looking into hacks for PlantUML and saw your repository. 

I had to write a post elsewhere and thought these notes might be useful to you for [other_layout_tricks.md](https://github.com/mattjhayes/PlantUML-Examples/blob/master/docs/Layout-Techniques/other_layout_tricks.md)

- [Hidden](https://stackoverflow.com/a/45103889): `a -[hidden]> b` (align l/r `-[hidden]>` and t/b `-[hidden]->`)
- [*n*-dashes][1]: `a --- b` (more dashes, longer line)
- [Adding transparent nodes][1] (here is an [example](https://forum.plantuml.net/3648/invisible-packages-improve-layout-diagrams-visible-packages))
- [norank](https://stackoverflow.com/a/61795202): `a -[norank]-> b` 
- Switch to [orthogonal mode](https://stackoverflow.com/a/48804742): `skinparam linetype ortho`

[1]: https://stackoverflow.com/a/48735216

Also found this, a [list of undocumented features](https://github.com/plantuml/plantuml/issues/261)

And here is an example:

```
@startuml
title Compact but Confusing Layout

class User
class Item
User "1" - "0..*" Item : borrow

class NonLoanableItem implements Item
class ReferenceBook implements NonLoanableItem

class LoanableItem implements Item
class FictionBook implements LoanableItem
class NonFictionBook implements LoanableItem

class CheckedOut {
  + dueDate : Date
}

User - LoanableItem
(User, LoanableItem) . CheckedOut
@enduml
```

```
@startuml
skinparam linetype ortho

title Better Layout

class User
class Item
User "1" -down- "0..*" Item : borrow

together {
  class NonLoanableItem implements Item
  class ReferenceBook implements NonLoanableItem
}

together {
    class LoanableItem implements Item
    class FictionBook implements LoanableItem
    class NonFictionBook implements LoanableItem
}

class CheckedOut {
  + dueDate : Date
}

User - LoanableItem
User -[Hidden]> CheckedOut
(User, LoanableItem) . CheckedOut
@enduml
```

**Comment by KyleKing** [comment]
Another to add. I figured out this morning that you can fix cardinality overlap by adding an extra leading/trailing space

```
@startuml

title Fixing Cardinality Overlap

class A
class B
A "1" -right- "0..*" B

class C
class D
C "1" -right- "  0..*" D

@enduml
```

**Comment by mattjhayes** [comment]
Thanks for the contributions Kyle. I've started making a few updates. Note that hidden lines was covered in another page. Have linked it to make this more clear

**Comment by VladimirAlexiev** [comment]
@KyleKing @mattjhayes  could you please add more items to https://github.com/plantuml/plantuml/issues/261? If you can't edit the description, add a comment and ping me to copy to description. 

@KyleKing how did you find out about the space??

**Comment by KyleKing** [comment]
@VladimirAlexiev can you clarify your question? Do you mean how I found out about PlantUML?

I had a class last fall that recommended DrawIO, but I wanted something that would be easy to work with and PlantUML was a much better choice. I made a project flow chart at work and have plans to use PlantUML in another project coming up

I don't think I have anything to add to https://github.com/plantuml/plantuml/issues/261. A handful of the notes above were already from that list

*Updated 10Feb2021 for clarity*

**Comment by VladimirAlexiev** [comment]
@KyleKing I mean the space in the cardinality string. Did you just experiment?

**Comment by KyleKing** [comment]
Oh yeah, just from experimentation. Haha, I can't tell if it is a bug or a feature

**Comment by VladimirAlexiev** [comment]
Given it some thought, it's not much of a feature. It just renders the space as an empty char, which shifts the cardinality label and avoids the overlap.
